[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cookebounds"
version = "0.1.0"
authors = [
    { name="joongyang" }
]
description = "Non-parametric threshold estimation using Extreme Value Theory and weight-calibrated Jackknife procedures."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Intended Audience :: Science/Research",
]
dependencies = [
    "numpy>=1.20.0",
]

[project.urls]
"Homepage" = "https://github.com/joongyang/cookebounds"
"Bug Tracker" = "https://github.com/joongyang/cookebounds/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["cookebounds*"]
exclude = ["tests*"]

